### ISSUE TITLE
Rename package to djangopreserialize

### ISSUE THREAD

**Issue by jahs** [bruth/django-preserialize#20]
Hi, the package name is `preserialize` but as this is Django-specific, would it be possible to rename it to `djangopreserialize` matching PyPi (following [PEP 8 (Package and Module Names)](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) guidelines)? [I have a generic pre-serialization module I'd like to open source called `preserialize` and just checking first to avoid a package name clash].

**Comment by bruth** [comment]
Hi James, I would prefer not too mainly because it is a breaking change. That being said there is a very unlikely chance both of our libraries will be used in the same project, so the chance of clashes is low.
